<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>11.0</LangVersion>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PlatformTarget>x86</PlatformTarget>
    <StartupObject>ZZZO.Program</StartupObject>
    <CefSharpExcludeSubProcessExe>true</CefSharpExcludeSubProcessExe>
    <LargeAddressAware>true</LargeAddressAware>
    <LargeAddressAwareAfterTargets>AfterBuild</LargeAddressAwareAfterTargets>
    <LargeAddressAwareTargetAssembly>$(MSBuildProjectDirectory)\bin\$(Configuration)\$(TargetFramework)\$(RuntimeIdentifier)\$(AssemblyName).exe</LargeAddressAwareTargetAssembly>
    <AssemblyVersion>0.0.7</AssemblyVersion>
    <ProductVersion>$(AssemblyVersion)</ProductVersion>
    <InformationalVersion>$(AssemblyVersion)$(SourceRevisionId)</InformationalVersion>
    <Copyright>Martin Rotter</Copyright>
    <Company>Martin Rotter</Company>
    <_SuppressWpfTrimError>true</_SuppressWpfTrimError>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="AppIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CefSharp.Wpf.NETCore" Version="151.3.170" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="LargeAddressAware" Version="1.0.6" PrivateAssets="all" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.2" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\3rd-party\TinyMCE\**">
      <Link>Data\TinyMceEditor\tinymce\%(RecursiveDir)\%(Filename)%(Extension)</Link>
      <TargetPath>Data\TinyMceEditor\tinymce\%(RecursiveDir)\%(Filename)%(Extension)</TargetPath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\resources\editor\**">
      <Link>Data\TinyMceEditor\%(RecursiveDir)\%(Filename)%(Extension)</Link>
      <TargetPath>Data\TinyMceEditor\%(RecursiveDir)\%(Filename)%(Extension)</TargetPath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\resources\styles\*">
      <Link>Data\Styles\%(Filename)%(Extension)</Link>
      <TargetPath>Data\Styles\%(Filename)%(Extension)</TargetPath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZZZO.Common\ZZZO.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="chromiumembeddedframework.runtime.win-arm64" Version="151.3.17" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="chromiumembeddedframework.runtime.win-x64" Version="151.3.17" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="chromiumembeddedframework.runtime.win-x86" Version="151.3.17" />
  </ItemGroup>

  <Target Name="SetPublishedAppHostLargeAddressAware" AfterTargets="Publish" Condition="'$(RuntimeIdentifier)' == 'win-x86' And Exists('$(PublishDir)$(AssemblyName).exe')">
    <SetLargeAddressAware FilePath="$(PublishDir)$(AssemblyName).exe" />
  </Target>

</Project>
